version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "click-to-earn-lambdas"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-185jbbuppdmhf"
s3_prefix = "click-to-earn-lambdas"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
