AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for EmailLambdaFunction

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  VerificationLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/VerificationLambda/
      Handler: VerificationLambda::VerificationLambda.Function::FunctionHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::573507721656:policy/CloudsWatch-Logs
        - arn:aws:iam::573507721656:policy/gameLiftPolicy
        - arn:aws:iam::573507721656:policy/NewPersonalDynamoPolicy
        - arn:aws:iam::573507721656:policy/InvokeLambdaUnity
        - arn:aws:iam::573507721656:policy/ses
      Events:
        VerificationLambdaApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /verify
            Method: get
            RequestParameters:
              - method.request.querystring.userId:
                  Required: true
                  Caching: false
              - method.request.querystring.walletAddress:
                  Required: true
                  Caching: false
            
  AccountLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/AccountLambda/
      Handler: AccountLambda::AccountLambda.Function::FunctionHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::573507721656:policy/CloudsWatch-Logs
        - arn:aws:iam::573507721656:policy/gameLiftPolicy
        - arn:aws:iam::573507721656:policy/NewPersonalDynamoPolicy
        - arn:aws:iam::573507721656:policy/InvokeLambdaUnity
        - arn:aws:iam::573507721656:policy/ses
      Events:
        AccountLambdaApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /account
            Method: post
            
  EconomyLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/EconomyLambda/
      Handler: EconomyLambda::EconomyLambda.Function::FunctionHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::573507721656:policy/CloudsWatch-Logs
        - arn:aws:iam::573507721656:policy/gameLiftPolicy
        - arn:aws:iam::573507721656:policy/NewPersonalDynamoPolicy
        - arn:aws:iam::573507721656:policy/InvokeLambdaUnity
        - arn:aws:iam::573507721656:policy/ses
      Events:
        EconomyLambdaApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /economy
            Method: post
            
  GameLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/GameLambda/
      Handler: GameLambda::GameLambda.Function::FunctionHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::573507721656:policy/CloudsWatch-Logs
        - arn:aws:iam::573507721656:policy/gameLiftPolicy
        - arn:aws:iam::573507721656:policy/NewPersonalDynamoPolicy
        - arn:aws:iam::573507721656:policy/InvokeLambdaUnity
        - arn:aws:iam::573507721656:policy/ses
      Events:
        GameLambdaApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /game
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  EmailLambda:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt VerificationLambda.Arn
  EmailLambdaIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt VerificationLambdaRole.Arn
